### ISSUE TITLE
Constant save bothering who use format on save features

### ISSUE THREAD

**Issue by herickwilke** [InSyncWithFoo/pyright-for-pycharm#10]
### What happened?

The plugin is constantly performing save, and too fast. For who use formatter triggered on save it becomes hard to work. 

https://github.com/InSyncWithFoo/pyright-for-pycharm/assets/47700306/c215052b-ed72-4521-8e0f-4a1d66ec6047

Is it possible to avoid that? 

I totally understand if this is the only way that the plugin can work.

### Steps to reproduce

Use some formatter on save. 

### Operating System

None

**Comment by herickwilke** [comment]
@InSyncWithFoo thanks! And no worries, I think that your plugin has a huge potential.

Yes, I have File Watchers configured that automatically format the file using Ruff. 

I was wondering if it was possible to maybe add a config like "[ ] Perform on save (warning: this will make the plugin not check on the fly)", something like this. It would do the trick I think. 

I'm also considering to disable the File Watchers on save and perform the format by using shortcuts instead.

**Comment by herickwilke** [comment]
I set a new shortcut to run File Watchers. I tested and it feels nice, I just need to get used to it now. I'll be trying to work like this today. If I get used to it no issues then. 

Thanks once more for the quick responses and support.

**Comment by DetachHead** [comment]
> That was an option I considered when I wrote the plugin, but it was delisted as all your files must be saved at the same time for Pyright to work correctly. You would either need to save them manually, which you probably don't want to, or wait until PyCharm does so automatically, which is somewhat unpredictable.

by default, pycharm auto-saves when the window loses focus. IMO, this behavior works fine with linters/type checkers that only run on save and in my experience it's not unpredictable. the [vscode mypy plugin](https://github.com/microsoft/vscode-mypy) also only runs on save and it works well for me when `files.autoSave` is set to `onFocusChange`.

it's really annoying when formatters run as you're typing so it would be great if there was an option to turn off this behavior

**Comment by KotlinIsland** [comment]
Can't it either wait till save to run, or create temp files and check those? That's how many other plugins work

**Comment by jonashaag** [comment]
Would you consider adding an option to set the save delay? This plugin causes lots of reloads when using something like uvicorn's `--reload`.

I'd be happy with either:

- Only check types upon manual save (I understand you need to save all files; in this case I'd be happy to have all files saved once I manually save one file)
- Only check types every N seconds

**Comment by jonashaag** [comment]
Nice thanks, I'll give it a try!

Would you consider an option to disabling saving altogether? I'm fine with Pyright to only run after I manually save, and with the state of all files when they were last manually saved.
